FIX mis_builder when user does not have time zone set.
Steps:

 - Install mis_builder
 - Empty time zone field of your user, if present
 - Create a MIS report template, following for example https://oca-mis-builder.readthedocs.io/en/latest/usage.html#reporting-on-non-accounting-data-queries

Get
`AttributeError: 'bool' object has no attribute 'upper'`